# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cslope <- function(x, directions) {
    .Call(`_bespatial_cslope`, x, directions)
}

